# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zamxmppim.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 631, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setObjectName("groupBox")
        self.L_envoi = QtWidgets.QLabel(self.groupBox)
        self.L_envoi.setGeometry(QtCore.QRect(280, 20, 71, 16))
        self.L_envoi.setObjectName("L_envoi")
        self.CB_envois = QtWidgets.QComboBox(self.groupBox)
        self.CB_envois.setGeometry(QtCore.QRect(360, 10, 131, 22))
        self.CB_envois.setObjectName("CB_envois")
        self.PB_Courbes = QtWidgets.QPushButton(self.groupBox)
        self.PB_Courbes.setGeometry(QtCore.QRect(500, 10, 93, 28))
        self.PB_Courbes.setObjectName("PB_Courbes")
        self.LPid = QtWidgets.QLabel(self.groupBox)
        self.LPid.setGeometry(QtCore.QRect(600, 10, 21, 16))
        self.LPid.setObjectName("LPid")
        self.LHeure = QtWidgets.QLabel(self.groupBox)
        self.LHeure.setGeometry(QtCore.QRect(10, 20, 55, 16))
        self.LHeure.setObjectName("LHeure")
        self.LTemps = QtWidgets.QLabel(self.groupBox)
        self.LTemps.setGeometry(QtCore.QRect(80, 20, 55, 16))
        self.LTemps.setObjectName("LTemps")
        self.LVoltage = QtWidgets.QLabel(self.groupBox)
        self.LVoltage.setGeometry(QtCore.QRect(150, 20, 55, 16))
        self.LVoltage.setObjectName("LVoltage")
        self.LTension = QtWidgets.QLabel(self.groupBox)
        self.LTension.setGeometry(QtCore.QRect(210, 20, 55, 16))
        self.LTension.setObjectName("LTension")
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 541, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(30, 210, 141, 201))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget.setGeometry(QtCore.QRect(0, 30, 151, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.L_envoi.setText(_translate("MainWindow", "essai_envoi"))
        self.PB_Courbes.setText(_translate("MainWindow", "Courbes"))
        self.LPid.setText(_translate("MainWindow", "pid"))
        self.LHeure.setText(_translate("MainWindow", "Heure(s):"))
        self.LTemps.setText(_translate("MainWindow", "0"))
        self.LVoltage.setText(_translate("MainWindow", "Voltage:"))
        self.LTension.setText(_translate("MainWindow", "0"))
